services:
    postgis:
        build:
            context: ./backend/postgis
            dockerfile: Dockerfile
        platform: linux/amd64
        environment:
            POSTGRES_DB: gisdb
            POSTGRES_USER: gisuser
            POSTGRES_PASSWORD: secret
        ports:
            - "5433:5432" # Cambiado a 5433 para evitar conflicto
        volumes:
            - postgis_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U gisuser -d gisdb"]
            interval: 10s
            timeout: 5s
            retries: 10

    geoserver:
        image: kartoza/geoserver
        platform: linux/amd64
        environment:
            GEOSERVER_ADMIN_USER: admin
            GEOSERVER_ADMIN_PASSWORD: geoserver
        ports:
            - "8080:8080"
        volumes:
            - ./geoserver_data:/opt/geoserver/data_dir

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8081:8080"
        depends_on:
            postgis:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgis:5432/gisdb
            SPRING_DATASOURCE_USERNAME: gisuser
            SPRING_DATASOURCE_PASSWORD: secret

    frontend:
        build:
            context: ./frontend/tsig-app
        ports:
            - "3000:5173"
        depends_on:
            - backend

volumes:
    postgis_data:
    geoserver_data:
